spring:
  jackson:
    time-zone: Asia/Seoul

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:/home/ubuntu/testdb;AUTO_SERVER=true
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 1000
    open-in-view: false

jwt:
  secret: sGk+uV5U3Pf1zThwZp5z+3Qyx4mJmT5L5xk+hOiZfqE=

#openai:
#  api-key:
#  image:
#    model: dall-e-2
#    size: 1024x1024